#!/bin/sh
# vim: set ts=4 sw=4 et:

PATH=/usr/bin:/usr/sbin

. /etc/runit/functions

msg "Welcome to Void!\n"

[ -r /etc/rc.conf ] && . /etc/rc.conf

# Start core services: one-time system tasks.
detect_virt
for f in /etc/runit/core-services/*.sh; do
    [ -r $f ] && . $f
done

dmesg >/var/log/dmesg.log

mkdir -p /run/runit
install -m100 /dev/null /run/runit/stopit

msg "Initialization complete, running stage 2...\n"
