#!/bin/sh
# vim: set ts=4 sw=4 et:

PATH=/usr/bin:/usr/sbin

runlevel=default
for arg in $(cat /proc/cmdline); do
    case $arg in
        single) echo "Initializing single user mode..."; runlevel=single;;
    esac
    if [ -d /etc/runit/runsvdir/"$arg" ]; then
        echo "Runlevel detected: '$arg' (via kernel cmdline)"
        runlevel="$arg"
    fi
done

[ -x /etc/rc.local ] && /etc/rc.local

# Create runlevel and then make it the default.
if [ -d /etc/runit/runsvdir/${runlevel} ]; then
    mkdir -p /run/runit/runsvdir
    ln -s /etc/runit/runsvdir/${runlevel} /run/runit/runsvdir/current
fi

exec env - PATH=$PATH \
    runsvdir -P /run/runit/runsvdir/current 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
