#!/bin/sh
# vim: set ts=4 sw=4 et:

PATH=/usr/bin:/usr/sbin

runlevel=default
for arg in $(cat /proc/cmdline); do
    case $arg in
        single) echo "Initializing single user mode..."; runlevel=single;;
    esac
done

# Setup first tty as unicode again, stage1 does not work correctly for tty1.
unicode_start

# Create runlevel and then copy services.
if [ -d /etc/runit/runsvdir/${runlevel} ]; then
    mkdir -p /run/runit/runsvdir
    cp -aP /etc/runit/runsvdir/${runlevel} /run/runit/runsvdir
    ln -s /run/runit/runsvdir/${runlevel} /run/runit/runsvdir/current
fi

exec env - PATH=$PATH \
    runsvdir -P /run/runit/runsvdir/current 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
