#!/bin/sh

tty=${PWD##*-}

[ -r conf ] && . conf

if [ -x /sbin/getty ]; then
	# busybox
	GETTY=getty
elif [ -x /sbin/agetty ]; then
	# util-linux
	GETTY=agetty
fi

exec setsid ${GETTY}${GETTY_ARGS:+ $GETTY_ARGS} \
	"${tty}" "${BAUD_RATE}" "${TERM_NAME}"
