#!/bin/sh

[ -r conf ] && . conf

tty=${PWD##*-}
if [ -x /sbin/getty ]; then
	# busybox
	GETTY=getty
elif [ -x /sbin/agetty ]; then
	# util-linux
	GETTY=agetty
fi

exec setsid ${GETTY}${GETTY_ARGS:+ $GETTY_ARGS} \
	"${tty}" "${baud_rate}" "${term_name}"
